version: '3'

services:
  app:
    build: ./app
    image: nextcloud:fpm-alpine-custom
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/media/nextcloud/data
      - nextcloud_config:/var/www/html/config
      - nextcloud_db:/var/run/mysqld
    ports:
      - '127.0.0.1:9001:9000'
    environment:
      - OVERWRITEWEBROOT=/cloud
      - NEXTCLOUD_DATA_DIR=/media/nextcloud/data

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/nextcloud'
  nextcloud_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/nextcloud/data'
  nextcloud_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/nextcloud/config'
  nextcloud_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/run/mysqld'

